# Generated by Django 5.1.6 on 2025-02-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='adress',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
