# Generated by Django 4.2.19 on 2025-02-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_remove_booking_created_at_remove_booking_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=7)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
