# Generated by Django 4.2.19 on 2025-02-26 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_earnings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earnings',
            new_name='Earning',
        ),
    ]
