# Generated by Django 4.2.19 on 2025-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_utilityexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilityexpense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='utilityexpense',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='utilityexpense',
            name='utility_type',
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='electricity_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='water_expense',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='month',
            field=models.IntegerField(),
        ),
    ]
