# Generated by Django 4.2.19 on 2025-02-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_remove_utilityexpense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilityexpense',
            name='total_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='electricity_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='month',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='water_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
