# Generated by Django 4.2.19 on 2025-02-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_utilityexpense_total_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
