# Generated by Django 4.2.19 on 2025-02-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_house_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
