# Generated by Django 4.2.19 on 2025-02-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_booking_booking_earnings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_earnings',
        ),
        migrations.RemoveField(
            model_name='house',
            name='earnings',
        ),
    ]
