# Generated by Django 4.2.19 on 2025-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0013_remove_booking_booking_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_earning',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='month',
            field=models.IntegerField(default=3),
        ),
    ]
