# Generated by Django 4.2.19 on 2025-03-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0014_booking_booking_earning_alter_utilityexpense_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_earning',
            new_name='booking_earnings',
        ),
    ]
