# Generated by Django 4.2.19 on 2025-03-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_rename_booking_earning_booking_booking_earnings'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='HouseEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_earnings', to='houses.house')),
            ],
        ),
    ]
