# Generated by Django 4.2.19 on 2025-03-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0018_remove_houseearning_house_delete_yearlyearning_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earning',
            new_name='MonthlyEarning',
        ),
    ]
