# Generated by Django 4.2.19 on 2025-03-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0019_rename_earning_monthlyearning'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
