# Generated by Django 5.1.6 on 2025-03-01 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_houseearning'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BookingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(default='Cleaning Fee', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.booking')),
            ],
        ),
    ]
