# Generated by Django 4.2.19 on 2025-03-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0023_monthlyexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.FloatField(),
        ),
    ]
