# Generated by Django 4.2.19 on 2025-03-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0025_alter_house_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='month',
            field=models.IntegerField(),
        ),
    ]
