# Generated by Django 4.2.19 on 2025-03-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0026_alter_monthlyexpense_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='month',
            field=models.DateField(),
        ),
    ]
