# Generated by Django 4.2.19 on 2025-03-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0029_remove_monthlyexpense_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseearning',
            name='month',
            field=models.DateField(),
        ),
    ]
