# Generated by Django 4.2.19 on 2025-03-04 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0030_alter_houseearning_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilityexpense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='utilityexpense',
            name='year',
        ),
        migrations.AddField(
            model_name='utilityexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='monthlyexpense',
            name='date',
            field=models.DateField(),
        ),
    ]
