# Generated by Django 4.2.19 on 2025-03-05 07:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0031_remove_utilityexpense_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingexpense',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bookingexpense',
            name='year',
        ),
        migrations.AddField(
            model_name='bookingexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='utilityexpense',
            name='date',
            field=models.DateField(default=datetime.date(2025, 3, 5)),
        ),
    ]
