# Generated by Django 4.2.19 on 2025-03-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0032_remove_bookingexpense_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyearning',
            name='month_name',
            field=models.DateField(),
        ),
    ]
