# Generated by Django 4.2.19 on 2025-03-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0033_alter_monthlyearning_month_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlyearning',
            name='year',
            field=models.DateField(),
        ),
    ]
