# Generated by Django 4.2.19 on 2025-03-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0034_alter_yearlyearning_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='house_photos/'),
        ),
    ]
