# Generated by Django 4.2.19 on 2025-03-06 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0035_house_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilityexpense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
