# Generated by Django 5.1.6 on 2025-06-06 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0040_cleaningfeesetting_alter_booking_cleaning_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningFeePerHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cleaning_fee', to='houses.house')),
            ],
        ),
    ]
